name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main # Asegúrate de que esta sea tu rama principal (o master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: # <<<<<<<<<< AÑADE ESTAS LÍNEAS
      contents: write # <<<<<<<<<< AÑADE ESTAS LÍNEAS
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Puedes ajustar la versión de Node.js si lo necesitas

      - name: Install dependencies
        run: npm install # O yarn install, pnpm install

      - name: Build Astro project
        run: npm run build # O yarn build, pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Asegúrate de que esta sea la carpeta de salida de Astro
          cname: # Si tienes un dominio personalizado, ponlo aquí. Ej: midominio.com